name: Run Python Script and Commit CSV

on:
  push:
    branches:
      - main # 触发动作的分支
  schedule:
    # 每天UTC时间00:00运行，按需调整
    - cron: '0 0 * * *'

jobs:
  build-and-commit-csv:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # 你的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywencai

    - name: Run Python script
      run: |
        python popularity.py
      
    - name: Upload CSV as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wencai-results
        path: 问财.csv

    - name: Commit and Push CSV to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f 问财.csv
        git commit -m 'Automatically update and commit 问财.csv' || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
